GET http://localhost:3000

###
GET http://localhost:3000/62f42859c7577741bc8868bc

###
POST http://localhost:3000
Content-Type: application/json

###
POST http://localhost:3000
Content-Type: application/json

{
  "title": "Estudar Teste",
  "description": "Criar um projeto simples com Teste"
}

###
PUT http://localhost:3000/62f433dae5a91c21f1e1ef68
Content-Type: application/json

{
  "title": "Estudar NestJS",
  "description": "Criar um projeto simples com NestJS"
}

###
DELETE http://localhost:3000/62f433dae5a91c21f1e1ef68